stellar-server/src/main/java/lab/stellar/faces/HelloBean.java
package lab.stellar.faces;

import javax.annotation.PostConstruct;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import java.io.Serializable;

@ManagedBean(name="helloBean")
@SessionScoped
public class HelloBean implements Serializable {


    private boolean rendering;

    public HelloBean(){
        System.out.println("hellobean constructor");
    }

    @PostConstruct
    public void init(){
        rendering = FacesContext.
                getCurrentInstance().
                getExternalContext().
                getRequestParameterMap().
                get("name") == null;
    }

    public boolean isRendering(){
        return rendering;
    }

    public String getName(String name){
        /*String name =
        FacesContext.
                getCurrentInstance().
                getExternalContext().
                getRequestParameterMap().
                get("name");*/
        System.out.println("name [" + name + "]");
        return name.toUpperCase();
    }

}

stellar-server/src/main/java/lab/stellar/faces/LocaleBean.java
package lab.stellar.faces;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.logging.Logger;

@ManagedBean
@SessionScoped
public class LocaleBean {

    Logger logger = Logger.getLogger(LocaleBean.class.getName());

    private String selectedLocale =
            FacesContext.
                    getCurrentInstance().
                    getViewRoot().
                    getLocale()
            .getLanguage();


    public String getSelectedLocale() {
        return selectedLocale;
    }

    public void setSelectedLocale(String selectedLocale) {
        FacesContext.
                getCurrentInstance().
                getViewRoot().
                setLocale( new Locale(selectedLocale) );
        this.selectedLocale = selectedLocale;
    }

    public void changeLocaleEvent(ValueChangeEvent e){
        logger.info("about to change locale to " + e.getNewValue());
        changeLocale(e.getNewValue().toString());
    }

    public void changeLocale(String code){

        logger.info("changing locale to [" + code + "]");
        /*FacesContext.
                getCurrentInstance().
                getViewRoot().
                setLocale( new Locale(code) );*/
    }

    public List<Locale> getSupportedLocales(){
        Iterator<Locale> itr =
                FacesContext.
                        getCurrentInstance().
                        getApplication().
                        getSupportedLocales();
        List<Locale> locales = new ArrayList<>();
        itr.forEachRemaining(l->locales.add(l));

        locales.add(FacesContext.
                getCurrentInstance().
                getApplication().
                getDefaultLocale()
        );

        return locales;
    }
}

stellar-server/src/main/java/lab/stellar/faces/SearchBean.java
package lab.stellar.faces;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

@ManagedBean
@ViewScoped
public class SearchBean {

    private String phrase;

    private int systemId;

    @PostConstruct
    public void initSystemId(){
        String systemIdString =
                FacesContext.
                        getCurrentInstance().
                        getExternalContext().
                        getRequestParameterMap().
                        get("systemId");
        if(systemIdString!=null && !systemIdString.trim().isEmpty()){
            this.systemId = Integer.parseInt(systemIdString);
        }
    }

    public boolean isPhrasePresent(){
        return phrase!=null && !phrase.trim().isEmpty();
    }

    public String getPhrase() {
        return phrase;
    }

    public void setPhrase(String phrase) {
        this.phrase = phrase;
    }

    public int getSystemId() {
        return systemId;
    }

    public void setSystemId(int systemId) {
        this.systemId = systemId;
    }


}

stellar-server/src/main/java/lab/stellar/faces/StellarBean.java
package lab.stellar.faces;

import lab.stellar.entities.Page;
import lab.stellar.entities.Planet;
import lab.stellar.entities.PlanetarySystem;
import lab.stellar.service.StellarService;
import lab.stellar.service.impl.StellarServiceImpl;
import org.primefaces.model.LazyDataModel;
import org.primefaces.model.SortOrder;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import java.lang.reflect.Field;
import java.util.List;
import java.util.Map;

@ManagedBean
@RequestScoped
public class StellarBean {

    @ManagedProperty("#{stellarService}")
    private StellarService service;

    @ManagedProperty("#{searchBean}")
    private SearchBean searchBean;



    LazyDataModel<Planet> lazyPlanets;

    @PostConstruct
    public void init(){
        lazyPlanets = new LazyDataModel<Planet>() {
            @Override
            public List<Planet> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, Object> filters) {

                Page<Planet> planetsPage = service.getPlanetsPage(
                        service.getSystemById(searchBean.getSystemId()),
                        (first/pageSize)+1,
                        pageSize
                );
                this.setRowCount((int)planetsPage.getTotal());
                return planetsPage.getItems();
            }
        };
    }


    public List<PlanetarySystem> getPlanetarySystems() {
        if (searchBean.isPhrasePresent()) {
            return service.getSystemsByName(searchBean.getPhrase());
        } else {
            return service.getSystems();
        }
    }

    public PlanetarySystem getPlanetarySystem(int systemId) {
        return service.getSystemById(systemId);
    }

    public List<Planet> getPlanets() {

        if (searchBean.isPhrasePresent()) {
            return service.getPlanets(service.getSystemById(searchBean.getSystemId()), searchBean.getPhrase());
        } else {
            return service.getPlanets(service.getSystemById(searchBean.getSystemId()));
        }
    }

    public LazyDataModel<Planet> getLazyPlanets(){

        return lazyPlanets;
    }

    public StellarService getService() {
        return service;
    }

    public void setService(StellarService service) {
        this.service = service;
    }


    public SearchBean getSearchBean() {
        return searchBean;
    }

    public void setSearchBean(SearchBean searchBean) {
        this.searchBean = searchBean;
    }
}

stellar-server/src/main/java/lab/stellar/servlet/HelloServlet.java
package lab.stellar.servlet;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

public class HelloServlet extends HttpServlet{

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        String name = "You";

        if(req.getParameterMap().containsKey("name")) {
            name = req.getParameter("name");
        }

        resp.getWriter().write("<html><body>Hey " + name + "!</body></html>");
    }
}

stellar-server/src/main/java/lab/stellar/servlet/PlanetsServlet.java
package lab.stellar.servlet;

import lab.stellar.entities.Page;
import lab.stellar.entities.Planet;
import lab.stellar.service.StellarService;
import lab.stellar.service.impl.StellarServiceImpl;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.logging.Logger;

public class PlanetsServlet extends HttpServlet {

    private Logger logger = Logger.getLogger(PlanetsServlet.class.getName());

    private StellarService service = new StellarServiceImpl();

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        int systemId = Integer.parseInt(req.getParameter("systemId"));

        if(systemId==3){
            throw new IllegalArgumentException("illegal system id");
        }
        logger.info("about to fetch planets of system " + systemId);

        int pageSize = 3;

        int pageNo = 1;
        if(req.getParameterMap().containsKey("pageNo")){
            pageNo = Integer.parseInt(req.getParameter("pageNo"));
        }

        Page<Planet> planetPage = service.getPlanetsPage(
                service.getSystemById(systemId),
                pageNo,
                pageSize
        );

        req.setAttribute("planets", planetPage);

        req.getRequestDispatcher("/WEB-INF/jsp/planets.jsp").forward(req, resp);
    }
}

stellar-server/src/main/java/lab/stellar/servlet/SystemsServlet.java
package lab.stellar.servlet;

import lab.stellar.entities.PlanetarySystem;
import lab.stellar.service.StellarService;
import lab.stellar.service.impl.StellarServiceImpl;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Logger;

public class SystemsServlet extends HttpServlet {

    private Logger logger = Logger.getLogger(SystemsServlet.class.getName());

    private StellarService service = new StellarServiceImpl();

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        logger.info("about to fetch planetary systems");

        List<PlanetarySystem> systems;
        if(req.getParameterMap().containsKey("systemId")) {
            int systemId = Integer.parseInt(req.getParameter("systemId"));
            systems = Arrays.asList(service.getSystemById(systemId));
        } else {
            systems = service.getSystems();
        }

        req.setAttribute("systems", systems);

        req.getRequestDispatcher("/WEB-INF/jsp/systems.jsp").forward(req, resp);

        /*StringBuilder sb = new StringBuilder();

        sb.append("<html><body>"+
                "<table><tr><th>Name</th><th>Star</th></tr>");

        systems.forEach(
                s-> sb.append("<tr><td>").append(s.getName()).append("</td><td>").append(s.getStar()).append("</td></tr>")
        );

        sb.append("</table></body></html>");

        resp.getWriter().write(sb.toString());*/

    }
}

stellar-server/src/main/webapp/jsf/addSystems.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
>

<h:body>


        <ui:composition template="template.xhtml">
            <ui:param name="displaySearch" value="false"/>
            <ui:define name="title">
                #{msg['label.planetary.system.add.title']}
            </ui:define>
            <ui:define name="content">

                <h:form>
                    <h:outputLabel>#{msg['label.planetary.system.name']}</h:outputLabel>
                    <h:inputText required="true" value="#{planetarySystemForm.name}"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.star']}</h:outputLabel>
                    <h:inputText id="star" required="true"  maxlength="10" value="#{planetarySystemForm.star}">
                        <f:validateLength minimum="2" maximum="10"/>
                    </h:inputText>
                    <h:message for="star" style="color: red"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.distance']}</h:outputLabel>
                    <h:inputText id="distance" value="#{planetarySystemForm.distance}">
                        <f:validateDoubleRange minimum="0"/>
                    </h:inputText>
                    <h:message for="distance" style="color: red"/>
                    <br/>
                    <h:outputLabel >#{msg['label.planetary.system.discovery']}</h:outputLabel>
                    <h:inputText id="discovery" value="#{planetarySystemForm.discovery}">
                        <f:convertDateTime type="date" pattern="yyyy-MM-dd"/>
                    </h:inputText>
                    <h:message for="discovery" style="color: red;"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.details']}</h:outputLabel>
                    <h:inputText id="details" value="#{planetarySystemForm.details}">
                        <f:converter converterId="urlConverter"/>
                    </h:inputText>
                    <h:message for="details" style="color: red;"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.next']}</h:outputLabel>
                    <h:selectBooleanCheckbox value="#{planetarySystemForm.next}"/>
                    <br/>
                    <h:commandButton
                            action="#{planetarySystemForm.add}"
                            value="${msg['label.planetary.system.add.button']}"/>
                </h:form>

            </ui:define>

        </ui:composition>

</h:body>

</html>

stellar-server/src/main/webapp/jsf/hello.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
>

<h:head>
    <title>JSF Hello World</title>
</h:head>
<h:body>
    <c:set var="customCriteria" value="#{helloBean.rendering}"/>

    <c:choose>
        <c:when test="#{not customCriteria}">
            <h:outputText value="Hello, #{helloBean.getName(param.name)}"/>
        </c:when>
        <c:otherwise>
            <h:outputText value="Hello, #{helloBean.getName('Jack')}"/>
        </c:otherwise>
    </c:choose>


</h:body>

</html>

stellar-server/src/main/webapp/jsf/planets.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui"
>

<h:body>

        <ui:composition template="template.xhtml">
            <ui:param name="displaySearch" value="true"/>

            <ui:define name="title">

                <h:outputFormat value="#{msg['label.planets.list.title']}">
                    <f:param value="#{stellarBean.getPlanetarySystem(searchBean.systemId).name}"/>
                </h:outputFormat>

            </ui:define>

            <ui:define name="content">

                <p:dataTable
                        value="#{stellarBean.lazyPlanets}"
                        var="p"
                        rows="3"
                        lazy="true"
                        paginator="true"
                        paginatorPosition="top"
                        paginatorTemplate="{PreviousPageLink} {PageLinks} {NextPageLink}"
                        currentPageReportTemplate="{startRecord} - {endRecord} of {totalRecords}"
                >
                    <p:column headerText="Id">
                        <h:outputText value="#{p.id}"/>
                    </p:column>
                    <p:column headerText="Name">
                        <h:outputText value="#{p.name}"/>
                    </p:column>
                </p:dataTable>

            </ui:define>

        </ui:composition>

</h:body>

</html>

stellar-server/src/main/webapp/jsf/search.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
>
<f:view>
    <div id="search">
        <span>SEARCH</span>
        <h:form styleClass="search-container" >
            <h:inputText value="#{searchBean.phrase}"/>
            <h:commandButton/>
        </h:form>
    </div>
</f:view>
</html>

stellar-server/src/main/webapp/jsf/systems.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:jsf="http://xmlns.jcp.org/jsf"
>

<h:body>


        <ui:composition template="template.xhtml">
            <ui:param name="displaySearch" value="true"/>
            <ui:define name="title">
                Planetary Systems
            </ui:define>
            <ui:define name="content">
                <h:dataTable id="systemsTable" value="#{stellarBean.planetarySystems}" var="s">
                    <h:column>
                        <f:facet name="header">#{msg['label.planetary.system.name']}</f:facet>
                        <h:link value="#{s.name}" outcome="planets">
                            <f:param name="systemId" value="#{s.id}"/>
                        </h:link>

                    </h:column>
                    <h:column>
                        <f:facet name="header">#{msg['label.planetary.system.star']}</f:facet>
                        <h:outputText value="#{s.star}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">#{msg['label.planetary.system.distance']}</f:facet>
                        <h:outputText value="#{s.distance}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">#{msg['label.planetary.system.discovery']}</f:facet>
                        <h:outputText value="#{s.discovery}">
                            <f:convertDateTime type="date" pattern="yyyy-MM-dd"/>
                        </h:outputText>
                    </h:column>
                    <h:column>
                        <f:facet name="header">#{msg['label.planetary.system.details']}</f:facet>
                        <h:outputLink value="#{s.details}">
                            View
                        </h:outputLink>
                    </h:column>
                </h:dataTable>

                <h:form>
                    <h:commandLink value="${msg['label.planetary.system.add.button']}">
                        <f:ajax execute="@form" render="systemForm" listener="#{planetarySystemForm.setDisplay(true)}"/>
                    </h:commandLink>
                </h:form>

                <div jsf:id="systemForm">


                <h:form  rendered="#{planetarySystemForm.display}">
                    <h:outputLabel>#{msg['label.planetary.system.name']}</h:outputLabel>
                    <h:inputText required="true" value="#{planetarySystemForm.name}"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.star']}</h:outputLabel>
                    <h:inputText id="star" required="true"  maxlength="10" value="#{planetarySystemForm.star}">
                        <f:validateLength minimum="2" maximum="10"/>
                    </h:inputText>
                    <h:message for="star" style="color: red"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.distance']}</h:outputLabel>
                    <h:inputText id="distance" value="#{planetarySystemForm.distance}">
                        <f:validateDoubleRange minimum="0"/>
                    </h:inputText>
                    <h:message for="distance" style="color: red"/>
                    <br/>
                    <h:outputLabel >#{msg['label.planetary.system.discovery']}</h:outputLabel>
                    <h:inputText id="discovery" value="#{planetarySystemForm.discovery}">
                        <f:convertDateTime type="date" pattern="yyyy-MM-dd"/>
                    </h:inputText>
                    <h:message for="discovery" style="color: red;"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.details']}</h:outputLabel>
                    <h:inputText id="details" value="#{planetarySystemForm.details}">
                        <f:converter converterId="urlConverter"/>
                    </h:inputText>
                    <h:message for="details" style="color: red;"/>
                    <br/>

                    <h:commandButton
                            value="${msg['label.planetary.system.add.button']}">
                    <f:ajax execute="@all" render="systemsTable systemForm" listener="#{planetarySystemForm.add}"/>
                </h:commandButton>
                </h:form>
                </div>

            </ui:define>

        </ui:composition>

</h:body>

</html>

stellar-server/src/main/webapp/jsf/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
>

<h:head>
    <title>Stellar</title>
    <h:outputStylesheet library="css" name="style.css"/>
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet"/>
</h:head>
<h:body>

    <header>
        <nav>
            <ul>
                <li class="active"><a
                        href="./systems.faces">Stellar Catalogue</a></li>
            </ul>
            <span>
                <h:form>
                    <h:selectOneMenu
                            value="#{localeBean.selectedLocale}"
                            onchange="submit()"
                            >
                        <f:selectItems
                                value="#{localeBean.supportedLocales}"
                                var="loc"
                                itemLabel="#{loc.getDisplayLanguage()}"
                                itemValue="#{loc.language}"

                        />
                    </h:selectOneMenu>
                </h:form>

            </span>
        </nav>
    </header>

    <article>

        <c:if test="#{displaySearch}">
            <ui:include src="search.xhtml"/>
        </c:if>

        <section class="data">
            <span><ui:insert name="title">TODO</ui:insert></span>

            <ui:insert name="content"/>

        </section>
    </article>



</h:body>

</html>